[build]
  base = "the-samples/reactions-react"
  publish = "dist"
  command = "pnpm build"

[build.environment]
  VITE_APP_URL = "https://tally-tool.frectonz.io"

# [context.production.environment]
#   VITE_APP_URL = "https://tally-tool.frectonz.io"

# [context.deploy-preview.environment]
#   VITE_APP_URL = "https://tally-tool.frectonz.io"

# [context.branch-deploy.environment]
#   VITE_APP_URL = "https://tally-tool.frectonz.io"
