name: CI
on:
  push:
    branches:
      - "**"
    paths:
      - the-lib/**

defaults:
  run:
    working-directory: the-lib

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: "pnpm"
          cache-dependency-path: './the-lib/pnpm-lock.yaml'

      - run: pnpm install --frozen-lockfile
      - run: pnpm run lint && pnpm run build
